### ISSUE TITLE
Mobile version?

### ISSUE THREAD

**Issue by Sirfrancis18** [roshanconnor123/Gdutils_Tgbot#3]
hi
is there a version that works without termux?
that works without the web server

**Comment by roshanconnor123** [comment]
I dont know of
Why not termux?
Also..Nodejs is compulsory for installation of this tool
So i cant

**Comment by Sirfrancis18** [comment]
I wanted to say a version for mobile, with termux but that a web server in linux is not necessary
Is possible?
