### ISSUE TITLE
I have done all steps and got success message but the bot is not responding to /help

### ISSUE THREAD

**Issue by iamLiquidX** [roshanconnor123/Gdutils_Tgbot#7]
<a href="https://ibb.co/FXPJLcT"><img src="https://i.ibb.co/yp35cKj/Screenshot-72.png" alt="Screenshot-72" border="0" /></a>

bot is not responding to /help. any help is appericiated.

**Comment by roshanconnor123** [comment]
It looks like you have messed something with your subdomain In cloudfare
Try to fix it
Thanks

**Comment by iamLiquidX** [comment]
not working for me i may have messes up somewhere.
